use_frameworks!

platform :ios, '12.2'

target 'Observatory_Example' do
  pod 'ObservatoryPod'
  pod 'ObservatoryPod/TracingZipkin'

  target 'Observatory_Tests' do
    inherit! :search_paths

    
  end
end
